<?php

/**
 * @file
 * Installation functions for tagged_text module.
 */

/**
 * Implements hook_field_schema().
 */
function tagged_text_field_schema($field) {
  
  $columns = array(
    'value' => array(
      'type' => 'varchar',
      'length' => 255,
      'not null' => FALSE,
    ),
  );
  // Return array that contains.
  return array(                 
    'columns' => $columns,
    'indexes' => array(
      'value' => array('value'),
    ),
  );
  
  
}